name: dart_code_metrics
version: 6.0.0
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev/
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/getting-started/

environment:
  sdk: '>=3.0.0 <4.0.0'

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer:
  analyzer_plugin:
  ansicolor:
  args:
  collection:
  crypto:
  dart_code_metrics_presets:
  file:
  glob:
  html:
  http:
  meta:
  path:
  platform:
  pub_updater:
  source_span:
  uuid:
  xml:
  yaml:

dev_dependencies:
  coverage:
  intl:
  lints:
  mocktail:
  test:

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
